spring.profiles.active: local


server:
  port: 8090

spring.datasource:
  url: jdbc:postgresql://localhost:5432/demodb
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver
  hikari:
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 20
    minimum-idle: 5
    idle-timeout: 120000

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  open-in-view: false
  show_sql: false
  generate-ddl: false
  hibernate:
    ddl-auto: none
  properties:
    hibernate.default_schema: demodb

spring.flyway.enabled: false